version: '3.4'
services:

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${CONFIG}/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env 
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/media-share/Complete Torrents:/downloads # downloads folder
      - ${CONFIG}/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/jackett:/config # config files

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/media-share/Incoming Torrents/downloads:/downloads # download folder
      - ${CONFIG}/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/sonarr:/config # config files
      - ${ROOT}/media-share/Complete Torrents/tv:/tv # movies folder
      - ${ROOT}/media-share/Incoming Torrents/tv:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/radarr:/config # config files
      - ${ROOT}/media-share/Complete Torrents/movies:/movies # movies folder
      - ${ROOT}/media-share/Incoming Torrents/movies:/downloads # download folder

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}                            # timezone, defined in .env
      - PUID=${PUID}                        # default user id, defined in .env
      - PGID=${PGID}                        # default group id, defined in .env
      - ADVERTISE_IP=https://metis.local:32400
      - HOSTNAME=metis
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CONFIG}/plex/db:/config           # plex database
      - ${CONFIG}/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/media-share:/data           # media library

#  grafana:
#    container_name: grafana
#    image: grafana/grafana:latest
#    # user: "999"
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - TZ=${TZ} # timezone, defined in .env
#      - GF_SERVER_ROOT_URL:http://metis.local
#      - GF_INSTALL_PLUGINS="grafana-clock-panel,grafana-simple-json-datasource,andig-darksky-datasource,grafana-piechart-panel"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./grafana:/var/lib/grafana
#    ports:
#      - 3000:3000

